{
  try {
    executeForResult(operation);
    Assert.fail("Should have given error");
  }
 catch (  OperationFailedException expected) {
  }
}
