{
  try {
    ut.begin();
    client1.invoke();
    client2.invoke(APPLICATION_EXCEPTION);
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  TestApplicationException e) {
  }
 finally {
    client3.invoke();
    ut.rollback();
  }
  assertEventLogClient1(ROLLBACK,VOLATILE_ROLLBACK);
  assertEventLogClient2(ROLLBACK,VOLATILE_ROLLBACK);
  assertEventLogClient3(ROLLBACK,VOLATILE_ROLLBACK);
}
