{
  Exception positiveTestCaseException=null;
  try {
    return testActionWithPermission(action,additionalRequiredPerms,namingContext,name,params);
  }
 catch (  Exception e) {
    positiveTestCaseException=e;
    return null;
  }
 finally {
    try {
      testActionWithoutPermission(action,additionalRequiredPerms,namingContext,name,params);
    }
 catch (    Exception e) {
      if (positiveTestCaseException == null) {
        throw e;
      }
 else {
        throw new Exception("Both positive and negative permission test for JNDI action " + action + " failed. The negative test case (which should have resulted in a security exception)"+ " failed with a message: "+ "("+ e.getClass().getName()+ "): "+ e.getMessage()+ ". The exception of the positive testcase"+ " is set up as the cause of this exception.",positiveTestCaseException);
      }
    }
    if (positiveTestCaseException != null) {
      throw positiveTestCaseException;
    }
  }
}
