{
  try {
    bean.callThrowException();
  }
 catch (  EJBException e) {
    final Exception cause1=e.getCausedByException();
    assertNotNull(cause1);
    assertEquals(RuntimeException.class,cause1.getClass());
    final Throwable cause2=cause1.getCause();
    assertNotNull(cause2);
    assertEquals(Exception.class,cause2.getClass());
    assertEquals("This is an app exception",cause2.getMessage());
  }
}
